{
 "title": "Smart (disks health)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serial_number",
    "label": "Serial number",
    "query": {
     "query": "label_values(smartctl_last_update,serial_number)"
    }
   },
   {
    "name": "attribute_name",
    "label": "Attribute name",
    "query": {
     "query": "label_values(smartctl_ata_smart_attribute_value,attribute)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "smart status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_smart_status", "legendFormat": "{{serial_number}}" }
   ]
  },
  {
   "title": "Device details ($serial_number)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Disk capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_user_capacity_bytes{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Interface current speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_interface_speed_current{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Interface max speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_interface_speed_max{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Power on time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_power_on_time_hours{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Power on time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_power_cycle_time{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Device temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_temperature{serial_number=\"${serial_number}\"}",
     "legendFormat": "capacity bytes"
    }
   ]
  },
  {
   "title": "Device attributes ($serial_number)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "$attribute_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "repeat": "attribute_name",
   "targets": [
    {
     "expr": "smartctl_ata_smart_attribute_value{serial_number=\"${serial_number}\", attribute=\"${attribute_name}\"}",
     "legendFormat": "{{attribute}}"
    }
   ]
  }
 ]
}